language: python
cache: pip
python:
    - "2.7"
    - "3.6"
install:
    - pip install -r requirements.txt
    - pip install -e .
script:
    - pytest -m "not needs_data" comptools
    - bash ci/build_docs.sh
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs/_build/html
    target_branch: gh-pages
    email: "github-pages-deploy@travis-ci.org"
    on:
        branch: master
        python: "2.7"
