name: cr-composition
channels:
  - conda-forge
dependencies:
  - six
  - numpy
  - pandas
  - pytables
  - matplotlib
  - dask
  - keras
  - scikit-learn
  - h5py
  - ipython
  - matplotlib
  - seaborn
  - tensorflow
  - jupyter
  - pytest
  - xgboost
  - scipy
  - healpy
  - mlxtend
  - pyprind
  - pymysql
  - root5
  - pip:
      - pycondor
