name: composition
channels:
  - defaults
  - conda-forge
dependencies:
  - six
  - numpy
  - pandas
  - pytables
  - matplotlib
  - dask
  - keras
  - Theano
  - scikit-learn
  - h5py
  - ipython
  - matplotlib
  - seaborn
  - tensorflow
  - jupyter
  - pytest
  - xgboost
  - scipy
  - healpy
  - mlxtend
  - pyprind
  - pymysql
  - pip:
      - pycondor
