name: cr-composition
channels:
  - conda-forge
dependencies:
  # Analysis requirements
  - six
  - numpy
  - pandas
  - pytables
  - matplotlib
  - dask
  - scikit-learn
  - h5py
  - ipython
  - matplotlib
  - seaborn
  - jupyter
  - xgboost
  - scipy
  - healpy
  - mlxtend
  - pyprind
  - root5
  - pip:
      - pycondor
  # Testing requirements
  - pytest
  - flake8
  # Documentation requirements
  - sphinx
  - numpydoc
  - sphinx_rtd_theme
