name: cr-composition
channels:
  - conda-forge
dependencies:
  # Analysis requirements
  - python=3.6
  - six
  - numpy
  - xarray
  - pandas
  - h5py
  - pytables
  - matplotlib
  - dask
  - scikit-learn
  - h5py
  - ipython
  - matplotlib
  - seaborn
  - jupyter
  - xgboost
  - scipy
  - healpy
  - mlxtend
  - pyprind
  - pyunfold
  # Deep learning stuff
  - keras
  - tensorflow
  # Stuff from PyPI (i.e. not on conda-forge)
  - pip:
      - pycondor
      - livelossplot

  # Testing requirements
  - pytest
  - flake8

  # Documentation requirements
  - sphinx
  - numpydoc
  - sphinx_rtd_theme
